active: true
derived: false
header: |
  Data backbone (defer)
level: 1.1.0
links: []
normative: false
ref: ''
reviewed: D441txIi5voFP0tteDYaFG5T2ArfwQ7B4aYxhZ9itbk=
text: |
  (defer) Full decomposition of this branch is deferred until it is scheduled.
